stages:
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - src/evaluate.py
    - src/train.py
    - data/processed/test.npz
    - models/model.pth
    params:
    - preprocess.image_size
    - train.num_filters
    - train.dense_units
    - train.dropout_rate
    outs:
    - plots/confusion_matrix.png
    metrics:
    - metrics.json:
        cache: false
