preprocess:
  val_size: 0.1
  seed: 42
  image_size: 32

train:
  num_filters: 64
  dense_units: 128           #256 to 128
  dropout_rate: 0.3          #0.5 to 0.3
  learning_rate: 0.0005      #0.01 to 0.0005
  epochs: 20
  batch_size: 64             #128 to 64
  augment_flip: true
  seed: 42
